log_path: "/share/u/caden/sae-auto-interp/scripts/run.log"

cache:
    dataset_repo: "stas/openwebtext-10k"
    dataset_split: "train"
    num_batches: 100
    minibatch_size: 128
    batch_len: 64
    n_features: 32768
    n_tokens: 5_120_000
    seed: 22

cot_explainer: 
    temperature: 0.0
    max_tokens: 1000
    l: "<<"
    r: ">>"

simple_explainer:
    temperature: 0.0
    max_tokens: 100

detection:
    max_tokens: 1000
    temperature: 0.0
    n_examples: 10
    seed: 22
    batch_size: 10

generation: 
    n_tests: 10
    temperature: 0.0