cache:
    dataset_repo: "togethercomputer/RedPajama-Data-1T-Sample"
    dataset_name: ""
    dataset_split: "train[:3%]"
    num_batches: 800
    minibatch_size: 128
    batch_len: 64
    n_features: 131072
    n_tokens: 5_120_000
    n_splits: 16
    n_neighbors: 10
    seed: 22
example:
    activation_threshold: 0.5
    l: "<<"
    r: ">>"
    l_ctx: 15
    r_ctx: 4
cot_explainer: 
    temperature: 0.0
    max_tokens: 1500
simple_explainer:
    temperature: 0.0
    max_tokens: 100
detection:
    max_tokens: 1000
    temperature: 0.0
    n_examples: 10
    seed: 22
    batch_size: 10
generation: 
    n_tests: 10
    temperature: 0.0